controller_list:
  - name: /panda/panda_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7

# controller_list:
#   - name: joint1_effort_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: true
#     joints: 
#       - panda_joint1

#   - name: joint2_effort_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: true
#     joints: 
#       - panda_joint2

#   - name: joint3_effort_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: true
#     joints: 
#       - panda_joint3

#   - name: joint4_effort_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: true
#     joints: 
#       - panda_joint4

#   - name: joint5_effort_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: true
#     joints: 
#       - panda_joint5

#   - name: joint6_effort_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: true
#     joints: 
#       - panda_joint6

#   - name: joint7_effort_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: true
#     joints: 
#       - panda_joint7
